const entry = (id, label, searchTerms = []) => Object.freeze({
  id,
  label,
  searchTerms: Object.freeze(searchTerms),
});

/**
 * Canonical profession catalogue shared by profile and creator targeting.
 * IDs are persisted and must remain stable even when a display label changes.
 * searchTerms are picker-only aliases; they never participate in video search.
 */
export const PROFESSIONS = Object.freeze([
  entry('accountant', 'Accountant', ['accounts', 'finance']),
  entry('actor', 'Actor', ['acting', 'performer']),
  entry('architect', 'Architect', ['architecture']),
  entry('artist', 'Artist', ['art', 'painter']),
  entry('author', 'Author', ['writer', 'novelist']),
  entry('banker', 'Banker', ['banking']),
  entry('barber', 'Barber', ['hairdresser', 'grooming']),
  entry('biologist', 'Biologist', ['biology', 'life science']),
  entry('business_analyst', 'Business Analyst', ['ba', 'analysis']),
  entry('business_owner', 'Business Owner', ['entrepreneur', 'shop owner']),
  entry('carpenter', 'Carpenter', ['woodworker', 'woodworking']),
  entry('chef', 'Chef', ['cook', 'cooking']),
  entry('chemist', 'Chemist', ['chemistry']),
  entry('civil_engineer', 'Civil Engineer', ['construction engineer']),
  entry('coach', 'Coach', ['trainer', 'mentor']),
  entry('content_creator', 'Content Creator', ['creator', 'influencer']),
  entry('copywriter', 'Copywriter', ['copy writing', 'advertising writer']),
  entry('customer_support_specialist', 'Customer Support Specialist', ['customer service', 'support']),
  entry('data_analyst', 'Data Analyst', ['analytics', 'business intelligence']),
  entry('data_scientist', 'Data Scientist', ['machine learning', 'data science']),
  entry('dentist', 'Dentist', ['dental', 'dentistry']),
  entry('designer', 'Designer', ['design', 'creative']),
  entry('digital_marketer', 'Digital Marketer', ['marketing', 'seo', 'social media']),
  entry('doctor', 'Doctor', ['physician', 'medicine', 'medical']),
  entry('economist', 'Economist', ['economics']),
  entry('electrician', 'Electrician', ['electrical technician']),
  entry('electrical_engineer', 'Electrical Engineer', ['electronics engineer']),
  entry('entrepreneur', 'Entrepreneur', ['founder', 'startup']),
  entry('event_planner', 'Event Planner', ['event manager', 'wedding planner']),
  entry('farmer', 'Farmer', ['farming', 'agriculture']),
  entry('fashion_designer', 'Fashion Designer', ['fashion', 'clothing designer']),
  entry('film_director', 'Film Director', ['director', 'filmmaker']),
  entry('financial_advisor', 'Financial Advisor', ['wealth advisor', 'financial planner']),
  entry('fitness_trainer', 'Fitness Trainer', ['personal trainer', 'gym trainer']),
  entry('flight_attendant', 'Flight Attendant', ['cabin crew', 'air hostess']),
  entry('food_technologist', 'Food Technologist', ['food science']),
  entry('game_developer', 'Game Developer', ['game programmer', 'gaming']),
  entry('graphic_designer', 'Graphic Designer', ['visual designer', 'graphics']),
  entry('hair_stylist', 'Hair Stylist', ['hairdresser', 'salon']),
  entry('hotel_manager', 'Hotel Manager', ['hospitality', 'hotelier']),
  entry('human_resources_professional', 'Human Resources Professional', ['hr', 'recruiter']),
  entry('interior_designer', 'Interior Designer', ['interiors', 'decorator']),
  entry('journalist', 'Journalist', ['reporter', 'news']),
  entry('lawyer', 'Lawyer', ['advocate', 'attorney', 'legal']),
  entry('librarian', 'Librarian', ['library science']),
  entry('makeup_artist', 'Makeup Artist', ['mua', 'beauty']),
  entry('management_consultant', 'Management Consultant', ['consulting', 'strategy']),
  entry('mechanic', 'Mechanic', ['automobile mechanic', 'technician']),
  entry('mechanical_engineer', 'Mechanical Engineer', ['mechanical']),
  entry('musician', 'Musician', ['music', 'instrumentalist']),
  entry('nurse', 'Nurse', ['nursing', 'healthcare']),
  entry('nutritionist', 'Nutritionist', ['dietitian', 'nutrition']),
  entry('occupational_therapist', 'Occupational Therapist', ['ot', 'therapy']),
  entry('operations_manager', 'Operations Manager', ['operations']),
  entry('optometrist', 'Optometrist', ['eye care', 'vision']),
  entry('pharmacist', 'Pharmacist', ['pharmacy', 'medicine']),
  entry('photographer', 'Photographer', ['photography', 'camera']),
  entry('physicist', 'Physicist', ['physics']),
  entry('physiotherapist', 'Physiotherapist', ['physical therapist', 'physio']),
  entry('pilot', 'Pilot', ['aviator', 'aviation']),
  entry('plumber', 'Plumber', ['plumbing']),
  entry('police_officer', 'Police Officer', ['police', 'law enforcement']),
  entry('product_designer', 'Product Designer', ['ux designer', 'industrial designer']),
  entry('product_manager', 'Product Manager', ['pm', 'product management']),
  entry('professor', 'Professor', ['lecturer', 'academic']),
  entry('project_manager', 'Project Manager', ['project management', 'pmp']),
  entry('psychologist', 'Psychologist', ['psychology', 'counsellor']),
  entry('public_relations_professional', 'Public Relations Professional', ['pr', 'communications']),
  entry('real_estate_agent', 'Real Estate Agent', ['realtor', 'property dealer']),
  entry('researcher', 'Researcher', ['research', 'scientist']),
  entry('sales_professional', 'Sales Professional', ['salesperson', 'business development']),
  entry('scientist', 'Scientist', ['science', 'research']),
  entry('security_professional', 'Security Professional', ['security guard', 'security officer']),
  entry('social_worker', 'Social Worker', ['ngo', 'community worker']),
  entry('software_engineer', 'Software Engineer', ['developer', 'programmer', 'coding']),
  entry('sound_engineer', 'Sound Engineer', ['audio engineer', 'sound design']),
  entry('sports_professional', 'Sports Professional', ['athlete', 'sportsperson']),
  entry('stock_trader', 'Stock Trader', ['trader', 'stock market']),
  entry('surgeon', 'Surgeon', ['surgery', 'medical']),
  entry('teacher', 'Teacher', ['educator', 'school teacher']),
  entry('technician', 'Technician', ['technical worker']),
  entry('therapist', 'Therapist', ['counselling', 'therapy']),
  entry('translator', 'Translator', ['interpreter', 'translation']),
  entry('travel_agent', 'Travel Agent', ['travel consultant', 'tourism']),
  entry('veterinarian', 'Veterinarian', ['vet', 'animal doctor']),
  entry('video_editor', 'Video Editor', ['editing', 'post production']),
  entry('videographer', 'Videographer', ['video production', 'cinematographer']),
  entry('web_developer', 'Web Developer', ['website developer', 'frontend', 'backend']),
  entry('writer', 'Writer', ['writing', 'content writer']),
  entry('aerospace_engineer', 'Aerospace Engineer', ['aeronautical engineer']),
  entry('agricultural_engineer', 'Agricultural Engineer', ['agriculture engineering']),
  entry('animator', 'Animator', ['animation', 'motion designer']),
  entry('anthropologist', 'Anthropologist', ['anthropology']),
  entry('app_developer', 'App Developer', ['mobile developer', 'android', 'ios']),
  entry('archaeologist', 'Archaeologist', ['archaeology']),
  entry('auditor', 'Auditor', ['audit', 'accounting']),
  entry('automobile_engineer', 'Automobile Engineer', ['automotive engineer']),
  entry('baker', 'Baker', ['baking', 'pastry']),
  entry('biomedical_engineer', 'Biomedical Engineer', ['medical engineering']),
  entry('chartered_accountant', 'Chartered Accountant', ['ca', 'accounting']),
  entry('cloud_engineer', 'Cloud Engineer', ['cloud computing', 'aws', 'azure']),
  entry('company_secretary', 'Company Secretary', ['cs', 'corporate compliance']),
  entry('construction_manager', 'Construction Manager', ['construction', 'site manager']),
  entry('cybersecurity_professional', 'Cybersecurity Professional', ['cyber security', 'infosec']),
  entry('database_administrator', 'Database Administrator', ['dba', 'database']),
  entry('devops_engineer', 'DevOps Engineer', ['devops', 'sre']),
  entry('environmental_scientist', 'Environmental Scientist', ['environment', 'ecology']),
  entry('fashion_stylist', 'Fashion Stylist', ['stylist', 'fashion']),
  entry('forensic_scientist', 'Forensic Scientist', ['forensics', 'crime lab']),
  entry('geologist', 'Geologist', ['geology', 'earth science']),
  entry('government_employee', 'Government Employee', ['civil servant', 'public sector']),
  entry('insurance_professional', 'Insurance Professional', ['insurance', 'underwriter']),
  entry('investment_banker', 'Investment Banker', ['investment banking', 'finance']),
  entry('lab_technician', 'Lab Technician', ['laboratory', 'medical lab']),
  entry('logistics_professional', 'Logistics Professional', ['supply chain', 'logistics']),
  entry('machine_learning_engineer', 'Machine Learning Engineer', ['ml engineer', 'ai engineer']),
  entry('marine_engineer', 'Marine Engineer', ['shipping engineer', 'naval engineer']),
  entry('network_engineer', 'Network Engineer', ['networking', 'network administrator']),
  entry('paramedic', 'Paramedic', ['emergency medical technician', 'emt']),
  entry('politician', 'Politician', ['politics', 'public representative']),
  entry('quality_assurance_engineer', 'Quality Assurance Engineer', ['qa', 'software tester']),
  entry('radiologist', 'Radiologist', ['radiology', 'medical imaging']),
  entry('robotics_engineer', 'Robotics Engineer', ['robotics', 'automation']),
  entry('seo_specialist', 'SEO Specialist', ['search engine optimization', 'seo']),
  entry('supply_chain_manager', 'Supply Chain Manager', ['supply chain', 'procurement']),
  entry('tax_consultant', 'Tax Consultant', ['taxation', 'tax advisor']),
  entry('ui_ux_designer', 'UI/UX Designer', ['ui designer', 'ux designer', 'product design']),
]);

const professionById = new Map(PROFESSIONS.map((profession) => [profession.id, profession]));

export const isValidProfessionId = (professionId) =>
  typeof professionId === 'string' && professionById.has(professionId);

export const getProfessionById = (professionId) =>
  professionById.get(professionId) || null;

export const normalizeProfessionIds = (professionIds) => {
  if (!Array.isArray(professionIds)) return [];
  return [...new Set(professionIds.map((id) => String(id).trim()).filter(isValidProfessionId))];
};

